server:
  port: 7777

spring:
  datasource:

    url: jdbc:mysql://120.26.128.116:3306/hahaha_videowebsite?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: liujiarong
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 120.26.128.116
    port: 6379

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId:
    accessKeySecret: 
    bucketName: web-management-hahaha
