server:
  port: 8989
spring:
  datasource:
    #url: jdbc:mysql://localhost/hahaha_security?characterEncoding=utf-8&serverTimezone=UTC

    url: jdbc:mysql://120.26.128.116:3306/hahaha_videowebsite?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: liujiarong
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 120.26.128.116
    port: 6379

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      #id-type: auto